# Generated by Django 4.2.30 on 2026-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
