# Generated by Django 4.2.30 on 2026-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_case_case_type_client_client_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_index',
        ),
        migrations.AddField(
            model_name='client',
            name='client_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
