# Generated by Django 4.2.30 on 2026-04-23 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='hearing_documents/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='management.hearing')),
            ],
        ),
    ]
