# Generated by Django 4.2.30 on 2026-05-06 18:57

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_historicalclient'),
    ]

    operations = [
        TrigramExtension(),
    ]
