# Generated by Django 4.2.30 on 2026-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_historicalinvoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tehsil',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='hearing_stage',
            field=models.CharField(db_index=True, default='Attendance', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='tehsil',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalhearing',
            name='hearing_stage',
            field=models.CharField(db_index=True, default='Attendance', max_length=150),
        ),
    ]
