# Generated by Django 4.2.30 on 2026-07-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0015_client_portal_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Property', 'Property'), ('Tax', 'Tax'), ('Corporate', 'Corporate'), ('Banking', 'Banking'), ('Constitutional', 'Constitutional'), ('Service Matters', 'Service Matters'), ('Consumer Court', 'Consumer Court'), ('Cyber Crime', 'Cyber Crime'), ('Intellectual Property', 'Intellectual Property'), ('Labour Court', 'Labour Court'), ('Arbitration', 'Arbitration')], default='Civil', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='category',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Property', 'Property'), ('Tax', 'Tax'), ('Corporate', 'Corporate'), ('Banking', 'Banking'), ('Constitutional', 'Constitutional'), ('Service Matters', 'Service Matters'), ('Consumer Court', 'Consumer Court'), ('Cyber Crime', 'Cyber Crime'), ('Intellectual Property', 'Intellectual Property'), ('Labour Court', 'Labour Court'), ('Arbitration', 'Arbitration')], default='Civil', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed', 'Closed'), ('Archived', 'Archived'), ('Active', 'Active')], default='Case Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed', 'Closed'), ('Archived', 'Archived'), ('Active', 'Active')], default='Case Accepted', max_length=50),
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Hearing', 'Hearing'), ('Document', 'Document'), ('Payment', 'Payment'), ('Note', 'Note'), ('StatusChange', 'StatusChange'), ('General', 'General')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='management.case')),
            ],
        ),
    ]
