# Generated by Django 4.2.30 on 2026-07-17 12:09

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_client_client_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='client_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cnic'], name='client_cnic_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['mobile_number'], name='client_mob_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
