# Generated by Django 4.2.30 on 2026-07-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0020_client_client_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Supreme Court', 'Supreme Court'), ('High Court', 'High Court'), ('District Court', 'District Court'), ('Civil Court', 'Civil Court'), ('Family Court', 'Family Court'), ('Sessions Court', 'Sessions Court'), ('Consumer Court', 'Consumer Court')], max_length=100)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=150, null=True)),
                ('judge', models.CharField(max_length=150)),
                ('court_room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCourt',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Supreme Court', 'Supreme Court'), ('High Court', 'High Court'), ('District Court', 'District Court'), ('Civil Court', 'Civil Court'), ('Family Court', 'Family Court'), ('Sessions Court', 'Sessions Court'), ('Consumer Court', 'Consumer Court')], max_length=100)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=150, null=True)),
                ('judge', models.CharField(max_length=150)),
                ('court_room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical court',
                'verbose_name_plural': 'historical courts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='case_court_gin_idx',
        ),
        migrations.RemoveField(
            model_name='case',
            name='district',
        ),
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='district',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='tehsil',
        ),
        migrations.AddField(
            model_name='historicalcourt',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cases', to='management.court'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='court',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.court'),
        ),
    ]
