# Generated by Django

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('management', '0023_populate_default_judge'),
    ]
    operations = [
        migrations.AlterField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cases', to='management.judge'),
        ),
    ]
