# Generated by Django 4.2.30 on 2026-07-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0024_alter_case_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='filing_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='hearing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='filing_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhearing',
            name='hearing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Court Hearing', 'Court Hearing'), ('Client Meeting', 'Client Meeting'), ('Filing Deadline', 'Filing Deadline'), ('Payment Due', 'Payment Due'), ('Internal Task', 'Internal Task'), ('Staff Leave', 'Staff Leave'), ('Public Holiday', 'Public Holiday'), ('Office Event', 'Office Event')], default='Office Event', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='management.case')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='management.client')),
                ('reference_consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='management.consultationrequest')),
                ('reference_hearing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='management.hearing')),
                ('reference_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='management.invoice')),
                ('reference_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='management.task')),
            ],
        ),
    ]
