# Generated by Django 4.2.30 on 2026-07-19 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_remove_historicalinvoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 19, 8, 8, 16, 663688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default='11111111-1111-1111-1111-111111111111', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.invoice'),
            preserve_default=False,
        ),
    ]
