# Generated by Django 4.2.30 on 2026-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_payment_created_at_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('Other', 'Other')], default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
