# Generated by Django 4.2.30 on 2026-07-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_message_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='portal_password',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='portal_password',
        ),
    ]
