# Generated by Django 4.2.30 on 2026-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_remove_client_portal_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Property', 'Property'), ('Tax', 'Tax'), ('Corporate', 'Corporate'), ('Banking', 'Banking'), ('Constitutional', 'Constitutional'), ('Service Matters', 'Service Matters'), ('Consumer Court', 'Consumer Court'), ('Cyber Crime', 'Cyber Crime'), ('Intellectual Property', 'Intellectual Property'), ('Labour Court', 'Labour Court'), ('Arbitration', 'Arbitration')], db_index=True, default='Civil', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost'), ('Closed - Settled', 'Closed - Settled'), ('Closed - Withdrawn', 'Closed - Withdrawn'), ('Closed - Dismissed', 'Closed - Dismissed'), ('Archived', 'Archived'), ('Active', 'Active'), ('Closed', 'Closed')], db_index=True, default='Case Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='case_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='category',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Property', 'Property'), ('Tax', 'Tax'), ('Corporate', 'Corporate'), ('Banking', 'Banking'), ('Constitutional', 'Constitutional'), ('Service Matters', 'Service Matters'), ('Consumer Court', 'Consumer Court'), ('Cyber Crime', 'Cyber Crime'), ('Intellectual Property', 'Intellectual Property'), ('Labour Court', 'Labour Court'), ('Arbitration', 'Arbitration')], db_index=True, default='Civil', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost'), ('Closed - Settled', 'Closed - Settled'), ('Closed - Withdrawn', 'Closed - Withdrawn'), ('Closed - Dismissed', 'Closed - Dismissed'), ('Archived', 'Archived'), ('Active', 'Active'), ('Closed', 'Closed')], db_index=True, default='Case Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhearing',
            name='hearing_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], db_index=True, default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], db_index=True, default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
