# Generated by Django 4.2.30 on 2026-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_case_case_number_alter_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Civil Trial', 'Civil Trial'), ('Criminal Trial', 'Criminal Trial'), ('Family Trial', 'Family Trial'), ('Complaint Cases', 'Complaint Cases'), ('Civil Appeal', 'Civil Appeal'), ('Criminal Appeal', 'Criminal Appeal'), ('Family Appeal', 'Family Appeal'), ('Revenue Cases', 'Revenue Cases'), ('Civil Revision', 'Civil Revision'), ('Criminal Revision', 'Criminal Revision'), ('Rent Controller', 'Rent Controller'), ('Writ Petition', 'Writ Petition'), ('Quashment', 'Quashment'), ('Service matter', 'Service matter'), ('Consumer Court', 'Consumer Court'), ('Labour Court', 'Labour Court'), ('Drug Court', 'Drug Court'), ('Banking Court', 'Banking Court'), ('Taxation / Corporate', 'Taxation / Corporate')], db_index=True, default='Civil Trial', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Motion', 'Motion'), ('Framing of Charge', 'Framing of Charge'), ('Submission of W/R/S', 'Submission of W/R/S'), ('Arguments on application', 'Arguments on application'), ('Scheduling Conference', 'Scheduling Conference'), ('ISSUES', 'ISSUES'), ('Plaintiff evidence', 'Plaintiff evidence'), ('Defendant evidence', 'Defendant evidence'), ('Statement of accused', 'Statement of accused'), ('Final arguments', 'Final arguments'), ('Order', 'Order'), ('Conciliation', 'Conciliation'), ('Re-conciliation', 'Re-conciliation')], db_index=True, default='Attendance', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='category',
            field=models.CharField(choices=[('Civil Trial', 'Civil Trial'), ('Criminal Trial', 'Criminal Trial'), ('Family Trial', 'Family Trial'), ('Complaint Cases', 'Complaint Cases'), ('Civil Appeal', 'Civil Appeal'), ('Criminal Appeal', 'Criminal Appeal'), ('Family Appeal', 'Family Appeal'), ('Revenue Cases', 'Revenue Cases'), ('Civil Revision', 'Civil Revision'), ('Criminal Revision', 'Criminal Revision'), ('Rent Controller', 'Rent Controller'), ('Writ Petition', 'Writ Petition'), ('Quashment', 'Quashment'), ('Service matter', 'Service matter'), ('Consumer Court', 'Consumer Court'), ('Labour Court', 'Labour Court'), ('Drug Court', 'Drug Court'), ('Banking Court', 'Banking Court'), ('Taxation / Corporate', 'Taxation / Corporate')], db_index=True, default='Civil Trial', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Motion', 'Motion'), ('Framing of Charge', 'Framing of Charge'), ('Submission of W/R/S', 'Submission of W/R/S'), ('Arguments on application', 'Arguments on application'), ('Scheduling Conference', 'Scheduling Conference'), ('ISSUES', 'ISSUES'), ('Plaintiff evidence', 'Plaintiff evidence'), ('Defendant evidence', 'Defendant evidence'), ('Statement of accused', 'Statement of accused'), ('Final arguments', 'Final arguments'), ('Order', 'Order'), ('Conciliation', 'Conciliation'), ('Re-conciliation', 'Re-conciliation')], db_index=True, default='Attendance', max_length=50),
        ),
    ]
