# Generated by Django 4.2.30 on 2026-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_alter_case_category_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Settled', 'Settled'), ('Withdrawn', 'Withdrawn'), ('Dismissed', 'Dismissed')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Settled', 'Settled'), ('Withdrawn', 'Withdrawn'), ('Dismissed', 'Dismissed')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
