# Generated by Django 4.2.30 on 2026-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_case_closure_reason_case_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalhearing',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
