# Generated by Django 4.2.30 on 2026-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_hearing_is_completed_historicalhearing_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appeal_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='certified_copy_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='execution_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='appeal_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='certified_copy_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='execution_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Settled', 'Settled'), ('Withdrawn', 'Withdrawn'), ('Dismissed', 'Dismissed'), ('Transferred', 'Transferred'), ('Disposed', 'Disposed'), ('Compromised', 'Compromised')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Settled', 'Settled'), ('Withdrawn', 'Withdrawn'), ('Dismissed', 'Dismissed'), ('Transferred', 'Transferred'), ('Disposed', 'Disposed'), ('Compromised', 'Compromised')], default='', max_length=50),
        ),
    ]
