# Generated by Django 4.2.30 on 2026-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_case_appeal_expected_case_certified_copy_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Motion', 'Motion'), ('Framing of Charge', 'Framing of Charge'), ('Submission of W/R/S', 'Submission of W/R/S'), ('Arguments on application', 'Arguments on application'), ('Scheduling Conference', 'Scheduling Conference'), ('ISSUES', 'ISSUES'), ('Plaintiff evidence', 'Plaintiff evidence'), ('Defendant evidence', 'Defendant evidence'), ('Statement of accused', 'Statement of accused'), ('Final arguments', 'Final arguments'), ('Order', 'Order'), ('Conciliation', 'Conciliation'), ('Re-conciliation', 'Re-conciliation'), ('Case Accepted', 'Case Accepted'), ('Consultation', 'Consultation'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Active', 'Active')], db_index=True, default='Attendance', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Motion', 'Motion'), ('Framing of Charge', 'Framing of Charge'), ('Submission of W/R/S', 'Submission of W/R/S'), ('Arguments on application', 'Arguments on application'), ('Scheduling Conference', 'Scheduling Conference'), ('ISSUES', 'ISSUES'), ('Plaintiff evidence', 'Plaintiff evidence'), ('Defendant evidence', 'Defendant evidence'), ('Statement of accused', 'Statement of accused'), ('Final arguments', 'Final arguments'), ('Order', 'Order'), ('Conciliation', 'Conciliation'), ('Re-conciliation', 'Re-conciliation'), ('Case Accepted', 'Case Accepted'), ('Consultation', 'Consultation'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Active', 'Active')], db_index=True, default='Attendance', max_length=50),
        ),
    ]
