# Generated by Django 4.2.30 on 2026-05-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='description',
            field=models.TextField(blank=True, default='Professional Legal Services'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default='Professional Legal Services'),
        ),
    ]
