# Generated by Django 4.2.30 on 2026-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_case_category_case_priority_historicalcase_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost'), ('Closed - Settled', 'Closed - Settled'), ('Closed - Withdrawn', 'Closed - Withdrawn'), ('Closed - Dismissed', 'Closed - Dismissed'), ('Archived', 'Archived'), ('Active', 'Active'), ('Closed', 'Closed')], default='Case Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Case Accepted', 'Case Accepted'), ('Documentation Pending', 'Documentation Pending'), ('Filing in Progress', 'Filing in Progress'), ('Filed', 'Filed'), ('Under Trial', 'Under Trial'), ('Evidence Stage', 'Evidence Stage'), ('Arguments Stage', 'Arguments Stage'), ('Judgment Reserved', 'Judgment Reserved'), ('Decided', 'Decided'), ('Appeal', 'Appeal'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost'), ('Closed - Settled', 'Closed - Settled'), ('Closed - Withdrawn', 'Closed - Withdrawn'), ('Closed - Dismissed', 'Closed - Dismissed'), ('Archived', 'Archived'), ('Active', 'Active'), ('Closed', 'Closed')], default='Case Accepted', max_length=50),
        ),
    ]
