# Generated by Django 4.2.30 on 2026-07-17 12:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_case_status_alter_historicalcase_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['opponent_name'], name='case_opp_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='client_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cnic'], name='client_cnic_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
