# Generated by Django 4.2.30 on 2026-07-17 12:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_case_case_opp_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_name_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_cnic_gin_idx',
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['case_number'], name='case_no_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['court'], name='case_court_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
