# Generated by Django 4.2.30 on 2026-07-17 17:20

from django.db import migrations
import uuid

def populate_default_judge(apps, schema_editor):
    Case = apps.get_model('management', 'Case')
    Judge = apps.get_model('management', 'Judge')
    Court = apps.get_model('management', 'Court')
    
    if Case.objects.filter(judge__isnull=True).exists():
        # Find or create a default court
        court = Court.objects.first()
        if not court:
            court = Court.objects.create(name='Default Court', type='Civil Court')
        
        # Create a default judge
        judge = Judge.objects.create(
            name='Unknown Judge',
            court=court,
            designation='Unknown'
        )
        
        # Assign to all cases with null judge
        Case.objects.filter(judge__isnull=True).update(judge=judge)

def reverse_default_judge(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_add_judge_model'),
    ]

    operations = [
        migrations.RunPython(populate_default_judge, reverse_default_judge),
    ]
